version: '3.8'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waste_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run build && npm run dev"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=waste_db
      - DB_PORT=3306
      - PORT=8001
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - ./back:/app

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    depends_on:
      - back

  imagepy:
    build:
      context: ./imagePy
      dockerfile: Dockerfile
    command: sh -c "pip install -r requirements.txt && func start"
    ports:
      - "7071:7071"
    volumes:
      - ./imagePy:/app

volumes:
  db_data: