describe('Login', () => {
  it('Connexion via API et accès au dashboard', () => {
    cy.visit('/auth/login')
    cy.get('input[name="email"]').type('testuser@example2.com')
    cy.get('input[name="password"]').type('password123')
    cy.get('button[type="submit"]').click()
    cy.loginByApi()
    cy.visit('/Dashboard/analyser')
    cy.url({ timeout: 50000 }).should('include', '/Dashboard/analyser')
    cy.contains('Invité(e)')
    cy.wait(3000)
    cy.get('button').contains('Se déconnecter').click()
    cy.visit('/auth/login')
    cy.url({ timeout: 50000 }).should('include', '/auth/login')
  })
})
